### ISSUE TITLE
The buffer is not copied correctly

### ISSUE THREAD

**Issue by malleor** [khrona/AwesomiumSharp#2]
As I've [noted](https://github.com/khrona/AwesomiumSharp/commit/7073d3b4a496bfa8efc77e0d44c60c87053264b3#commitcomment-554936) in a code, the render buffer is not entirely copied, resulting in a [glitch](https://docs.google.com/leaf?id=0B-nphIAP9349N2VmZDAwNTUtNWQyMC00ZWYzLWI3ODctNjkyZWRlNmVlODY3&hl=pl) in the bottom of a render.

**Comment by Perikles** [comment]
Hello,

Thank you for your notes. This code was actually a partial remnant from an older technique. It has been completely removed from the next release of Awesomium.NET (formerly AwesomiumSharp).

Until the next update, you can apply any of the following two techniques:

## Replace all the contents of _DrawBuffer( RenderBuffer rBuffer, ref Bitmap b )_ with the following code:

```
        if ( b == null || b.Width != rBuffer.Width || b.Height != rBuffer.Height )
        {
            try
            {
                if ( b != null )
                    b.Dispose();

                b = new Bitmap(
                    rBuffer.Width,
                    rBuffer.Height,
                    rBuffer.Rowspan,
                    PixelFormat.Format32bppArgb,
                    rBuffer.Buffer );
            }
            catch { /* */ }
            finally
            {
                GC.Collect();
            }
        }
```
- OR -

## Replace the _unsafe_ block with:

```
        rBuffer.CopyTo( bits.Scan0, bits.Stride, 4, false );
```

Either one will do the job.

In the next release, we will be introducing a new **WinForms WebControl**. What's more, performance has been seriously improved in both the WPF as well as the new WinForms control.

Regards,
Perikles

**Comment by malleor** [comment]
Awesome, thank you.
